#!/usr/bin/env python3
"""Generate Space Watch's bundled bright-star table from the Yale Bright Star Catalog.

Input: bsc5-short.json from https://github.com/brettonw/YaleBrightStarCatalog
(BSC5, J2000 positions; Hoffleit & Warren 1991, via the Harvard/CfA and NASA
HEASARC distributions). Output: examples/space-watch-module/ui/space-stars.js with
stars of V <= 3.5 and the asterism lines the dome draws. The asterism stars are
checked against their Bayer letters so a renumbered input fails loudly.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'examples/space-watch-module/ui/space-stars.js'
LIMIT = 3.5
# name, HR path (consecutive pairs are drawn), expected Bayer letter per HR
ASTERISMS = [
    ('Big Dipper', [[5191, 5054, 4905, 4660, 4301, 4295, 4554, 4660]]),
    ('Cassiopeia', [[21, 168, 264, 403, 542]]),
    ('Orion', [[2061, 1790], [1790, 1852, 1903, 1948, 2061], [1948, 2004], [1852, 1713]]),
    ('Northern Cross', [[7924, 7796, 7417], [7949, 7796, 7528]]),
]
BAYER = {5191: ('η', 'UMa'), 5054: ('ζ', 'UMa'), 4905: ('ε', 'UMa'), 4660: ('δ', 'UMa'), 4301: ('α', 'UMa'),
         4295: ('β', 'UMa'), 4554: ('γ', 'UMa'), 21: ('β', 'Cas'), 168: ('α', 'Cas'), 264: ('γ', 'Cas'),
         403: ('δ', 'Cas'), 542: ('ε', 'Cas'), 2061: ('α', 'Ori'), 1790: ('γ', 'Ori'), 1852: ('δ', 'Ori'),
         1903: ('ε', 'Ori'), 1948: ('ζ', 'Ori'), 2004: ('κ', 'Ori'), 1713: ('β', 'Ori'), 7924: ('α', 'Cyg'),
         7796: ('γ', 'Cyg'), 7417: ('β', 'Cyg'), 7949: ('ε', 'Cyg'), 7528: ('δ', 'Cyg')}


def ra(text):
    h, m, s = re.findall(r'[\d.]+', text)
    return round((int(h) + int(m) / 60 + float(s) / 3600) * 15, 4)


def dec(text):
    d, m, s = re.findall(r'[\d.]+', text)
    return round((-1 if text.strip().startswith('-') else 1) * (int(d) + int(m) / 60 + float(s) / 3600), 4)


def generate(source):
    rows = {int(x['HR']): x for x in json.loads(Path(source).read_text()) if 'RA' in x and 'V' in x}
    for hr, (letter, const) in BAYER.items():
        x = rows[hr]
        assert x.get('B', '').startswith(letter) and x.get('C') == const, (hr, x)
    keep = sorted(hr for hr, x in rows.items() if float(x['V']) <= LIMIT or hr in BAYER)
    index = {hr: i for i, hr in enumerate(keep)}
    stars = [[ra(rows[hr]['RA']), dec(rows[hr]['Dec']), float(rows[hr]['V']), rows[hr].get('N')] for hr in keep]
    lines = [[name, [[index[hr] for hr in path] for path in paths]] for name, paths in ASTERISMS]
    body = ',\n'.join(json.dumps(s, ensure_ascii=False, separators=(',', ':')) for s in stars)
    OUT.write_text(
        '"use strict";\n'
        '// Generated by scripts/space_watch_stars.py from the Yale Bright Star Catalog\n'
        f'// (BSC5, J2000). Stars with V <= {LIMIT}: [RA deg, Dec deg, V mag, name].\n'
        'const SpaceStars = {\n'
        f'  stars: [\n{body}\n  ],\n'
        f'  asterisms: {json.dumps(lines, ensure_ascii=False, separators=(",", ":"))},\n'
        '};\n'
        'if (typeof module !== "undefined") module.exports = SpaceStars;\n')
    print(f'{len(stars)} stars, {len(lines)} asterisms -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('source', type=Path)
    generate(p.parse_args().source)
